services:
  postgres:
    image: postgres:15.0-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "passw@rd"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  api:
    build:
      context: ./
      dockerfile: conf/api/Dockerfile
    restart: always
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
      - vendor:/api/vendor
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: ./
      dockerfile: conf/web/Dockerfile
    restart: always
    ports:
      - "3030:3000"
    volumes:
      - ./web:/web
      - node_modules:/web/node_modules
    command: yarn dev
    environment:
      - HOST=0.0.0.0
      - WATCHPACK_POLLING=true
    depends_on:
      - api

volumes:
  vendor:
  node_modules: